// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBusTicketing.Data;

#nullable disable

namespace Ticket.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartBusTicketing.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            Action = "Khởi tạo hệ thống và gán quyền Quản lý (MANAGER) cho manager@gmail.com",
                            CreatedAt = new DateTime(2026, 9, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            IpAddress = "127.0.0.1",
                            UserId = "usr-adm-001"
                        });
                });

            modelBuilder.Entity("SmartBusTicketing.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toàn quyền quản lý tài khoản, phân quyền và xem nhật ký an ninh",
                            RoleCode = "ADMIN",
                            RoleName = "Quản trị hệ thống"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quản lý tuyến xe, lịch chạy, điều xe, duyệt ưu đãi và xem báo cáo",
                            RoleCode = "MANAGER",
                            RoleName = "Quản lý"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sử dụng app di động để quét mã QR soát vé và cập nhật sự cố trễ chuyến",
                            RoleCode = "DRIVER",
                            RoleName = "Tài xế"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tra cứu tuyến, chọn ghế, thanh toán vé, đăng ký vé tháng và xem bản đồ GPS",
                            RoleCode = "USER",
                            RoleName = "Người dùng"
                        });
                });

            modelBuilder.Entity("SmartBusTicketing.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentityCardEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identity_card_encrypted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_encrypted");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("salt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = "usr-adm-001",
                            CreatedAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            IdentityCardEncrypted = "enc_aes_ADM01",
                            PasswordHash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            PhoneEncrypted = "enc_aes_0981234567",
                            RoleId = 1,
                            Salt = "a1b2c3d4",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 9, 23, 19, 49, 16, 736, DateTimeKind.Utc).AddTicks(7946)
                        },
                        new
                        {
                            UserId = "usr-opr-001",
                            CreatedAt = new DateTime(2026, 9, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            Email = "manager@gmail.com",
                            FullName = "Quản Lý",
                            IdentityCardEncrypted = "enc_aes_QL01",
                            PasswordHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                            PhoneEncrypted = "enc_aes_0972345678",
                            RoleId = 2,
                            Salt = "b2c3d4e5",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 9, 23, 19, 49, 16, 736, DateTimeKind.Utc).AddTicks(7980)
                        },
                        new
                        {
                            UserId = "usr-drv-001",
                            CreatedAt = new DateTime(2026, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "taixe@gmail.com",
                            FullName = "Lê Văn Tài",
                            IdentityCardEncrypted = "enc_aes_TX01",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            PhoneEncrypted = "enc_aes_0963456789",
                            RoleId = 3,
                            Salt = "c3d4e5f6",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 9, 23, 19, 49, 16, 736, DateTimeKind.Utc).AddTicks(7988)
                        },
                        new
                        {
                            UserId = "usr-cus-001",
                            CreatedAt = new DateTime(2026, 9, 5, 10, 15, 0, 0, DateTimeKind.Utc),
                            Email = "user@gmail.com",
                            FullName = "Hoàng Minh Đức",
                            IdentityCardEncrypted = "enc_aes_NV01",
                            PasswordHash = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
                            PhoneEncrypted = "enc_aes_0915678901",
                            RoleId = 4,
                            Salt = "e5f6g7h8",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2026, 9, 23, 19, 49, 16, 736, DateTimeKind.Utc).AddTicks(7995)
                        });
                });

            modelBuilder.Entity("SmartBusTicketing.Models.AuditLog", b =>
                {
                    b.HasOne("SmartBusTicketing.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBusTicketing.Models.User", b =>
                {
                    b.HasOne("SmartBusTicketing.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartBusTicketing.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartBusTicketing.Models.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
